export enum Technology {
  REACT = 'React',
  NEXTJS = 'Next.js',
  ANGULAR = 'Angular',
  VUE = 'Vue',
  SVELTE = 'Svelte',
  FLUTTER = 'Flutter',
  NODE = 'Node',
  EXPRESS = 'Express.js',
  TYPEORM = 'TypeORM',
  MONGODB = 'MongoDB',
  MYSQL = 'MySQL',
  POSTGRESQL = 'PostgreSQL',
  TYPESCRIPT = 'TypeScript',
  JAVASCRIPT = 'JavaScript',
  HTML = 'HTML',
  CSS = 'CSS',
  SASS = 'Sass',
  TAILWIND = 'TailwindCSS',
  PROVIDER = 'Provider',
}
