import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import { Header } from '@/components/header/Header';
import BaseView from '@/components/base-view/BaseView';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang={'en'}>
      <body className={'h-screen bg-slate-100'}>
        <BaseView className={'w-full items-center h-full'} >
          <Header />
          <BaseView className={'w-full lg:w-2/3 h-full'}>{children}</BaseView>
        </BaseView>
      </body>
    </html>
  );
}
